<?php

namespace PlatformBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbrComments()
    {
        return $this->createQueryBuilder('c')
    ->select('COUNT(c)')
    ->getQuery()
    ->getSingleScalarResult();
    }
}
