<?php

namespace PlatformBundle\Repository;

/**
 * ImageStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageStoryRepository extends \Doctrine\ORM\EntityRepository
{
}
