<?php

namespace PlatformBundle\Repository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStories()
    {
        $query = $this->createQueryBuilder('s')
            ->leftJoin('s.imageStory', 'i')
            ->addSelect('i')
            ->leftJoin('s.category', 'c')
            ->addSelect('c')
            ->leftJoin('s.user', 'u')
            ->addSelect('u')
            ->orderBy('s.date', 'DESC')
            ->getQuery()
            ->getResult();

        return $query;
    }

   

    
}
